# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sistema.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'sistema.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsistema.proto\x12\nbiblioteca\"&\n\x05Livro\x12\x0e\n\x06titulo\x18\x01 \x01(\t\x12\r\n\x05\x61utor\x18\x02 \x01(\t\"\x1c\n\x08Resposta\x12\x10\n\x08mensagem\x18\x01 \x01(\t\"\x07\n\x05Vazio2\x82\x01\n\x11ServicoBiblioteca\x12\x39\n\x0e\x41\x64icionarLivro\x12\x11.biblioteca.Livro\x1a\x14.biblioteca.Resposta\x12\x32\n\nPegarLivro\x12\x11.biblioteca.Vazio\x1a\x11.biblioteca.Livrob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sistema_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LIVRO']._serialized_start=29
  _globals['_LIVRO']._serialized_end=67
  _globals['_RESPOSTA']._serialized_start=69
  _globals['_RESPOSTA']._serialized_end=97
  _globals['_VAZIO']._serialized_start=99
  _globals['_VAZIO']._serialized_end=106
  _globals['_SERVICOBIBLIOTECA']._serialized_start=109
  _globals['_SERVICOBIBLIOTECA']._serialized_end=239
# @@protoc_insertion_point(module_scope)
